---
title: "Bullshitter Expt 4"
author: "Lauren Oey"
date: "3/7/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lme4)
library(gridExtra)
library(cowplot)
library(stats4)
library(scales)
source("lying_modelFunctions.R")
knitr::opts_chunk$set(echo = TRUE)

bs <- read.csv("raw.csv")
glimpse(bs)
summary(bs)

bs <- bs %>%
  mutate(lie = drawnRed != reportedDrawn,
         player.bullshitter = ifelse(roleCurrent == "bullshitter", "human", "computer"),
         player.bullshitDetector = ifelse(roleCurrent == "bullshitDetector", "human", "computer"))
```

```{r}
exclude.sampling <- bs %>%
  filter(reportedDrawn > 10) %>%
  .$subjID

length(unique(exclude.sampling))
```

```{r}
catch <- bs %>%
  filter(catchKey != -1) %>%
  group_by(subjID) %>%
  summarise(catchCorrect = sum(catchKey == catchResponse))

ggplot(catch, aes(x=catchCorrect)) +
  geom_bar()

exclude.catch <- catch %>%
  filter(catchCorrect <= 0.75*max(catchCorrect)) %>%
  .$subjID

length(exclude.catch)
```

```{r include=FALSE}
# bs %>%
#   filter(roleCurrent == "bullshitter", !subjID %in% exclude.catch, !subjID %in% exclude.sampling) %>%
#   mutate(badLie = drawnRed > reportedDrawn) %>%
#   group_by(subjID) %>%
#   summarise(badLie.prop = sum(badLie)/n()) %>%
#   ggplot(aes(x=badLie.prop)) + 
#   geom_bar(aes(y = (..count..)/sum(..count..))) +
#   scale_x_continuous("Proportion of Lies Produced with Reported < Actual") +
#   scale_y_continuous("Proportion of Participants") +
#   theme_bw()
# ggsave("img/counterintuitiveLies.png")
# 
# # Participants who generated bad lies for more than 1/4 of their turns
# excluded <- bs %>%
#   filter(roleCurrent == "bullshitter", !subjID %in% exclude.catch, !subjID %in% exclude.sampling) %>%
#   mutate(badLie = drawnRed > reportedDrawn) %>%
#   group_by(subjID) %>%
#   summarise(badLie.prop = sum(badLie)/n())
#   
# excluded %>%
#   filter(badLie.prop > .2, !subjID %in% exclude.catch) %>%
#   select(subjID, badLie.prop) %>%
#   arrange(desc(badLie.prop))
# 
# excluded %>%
#   ungroup() %>%
#   summarise(badLiar.prop = sum(badLie.prop > 0)/n())
```

```{r}
bs.final <- bs %>%
  filter(!subjID %in% exclude.catch, !subjID %in% exclude.sampling, exptPart == "trial")

# # of participants who completed the task
length(unique(bs$subjID))

# # of participants who passed the attention check criteria
length(unique(bs.final$subjID))

# total # of participants excluded
length(unique(bs$subjID)) - length(unique(bs.final$subjID))
```

```{r}
bs.final %>%
  select(subjID, probabilityRed) %>%
  unique() %>%
  group_by(probabilityRed) %>%
  summarise(count = n())
```

# Model Predictions

## Recursive Inference Model

```{r}
numSims = 100

df.unif <- data.frame(role=factor(),
                      p=numeric(), 
                      decay=numeric(),
                      ks=numeric(), # ksay in Detector, k in Liar
                      n=numeric(),
                      val=numeric(),
                      se=numeric()) # prop in Detector, expLie in Liar
for(i in c(0.2, 0.5, 0.8)){
  for(j in c(0.1, 0.25, 0.5)){
    for(k in c(0.25, 1, 4)){
      ALPH = k
      for(l in c(0, 0.8, 1)){
        BET = l
        sim.D <- t(replicate(numSims, recurse.D(j, i, rep(0.1,11))))
        prop <- colMeans(sim.D)
        se <- prop * (1-prop) / sqrt(numSims)
        df.unif <- bind_rows(df.unif, data.frame(role="Detector", p=i, decay=j, alpha=k, beta=l, ks=0:10, n=numSims, val=prop, se=se))
        
        sim.L <- t(replicate(numSims, exp.ksay(i, recurse.D(j, i, rep(0.1,11)))))
        expLie <- colMeans(sim.L)
        se <- apply(sim.L, 2, sd) / sqrt(numSims)
        df.unif <- bind_rows(df.unif, data.frame(role="Liar", p=i, decay=j, alpha=k, beta=l, ks=0:10, n=numSims, val=expLie, se=se))
        
        sim.D2 <- t(replicate(numSims, recurse.L(j, i, rep(0.1,11))))
        prop <- colMeans(sim.D2)
        se <- prop * (1-prop) / sqrt(numSims)
        df.unif <- bind_rows(df.unif, data.frame(role="Detector2", p=i, decay=j, alpha=k, beta=l, ks=0:10, n=numSims, val=prop, se=se))
      }
    }
  }
}

condColors.diff = c("p = 0.2" = "blue",
               "p = 0.5" = "purple",
               "p = 0.8" = "red")

lie.recurse <- df.unif %>%
  filter(role=="Liar", decay==0.25, alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_abline(size=4, intercept = 0, slope = 1, colour="forestgreen", linetype=2) +
  geom_line(size=4, alpha=0.9) +
  scale_x_continuous("True Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected Reported", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values=condColors.diff) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.title = element_text(size=28),
        axis.text = element_text(size=24))
ggsave("img/modelRecurse_lie.png", lie.recurse, height=8, width=7.5)

detect.recurse <- df.unif %>%
  filter(role=="Detector", decay==0.25, alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(size=4, alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(BS)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.title = element_text(size=28),
        axis.text = element_text(size=24))
ggsave("img/modelRecurse_detect.png", detect.recurse, height=8, width=7.5)


detectProb.recurse <- df.unif %>%
  filter(role=="Detector2", decay==0.25, alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(size=4, alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(Lie)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.title = element_text(size=28),
        axis.text = element_text(size=24))
ggsave("img/modelRecurse_detect2.png", detectProb.recurse, height=8, width=7.5)
```


## Varying decay

```{r}
## Liar
liar.decay <- df.unif %>%
  filter(role=="Liar", alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_abline(intercept = 0, slope = 1, colour="forestgreen", linetype=2) +
  geom_line(alpha=0.9) +
  scale_x_continuous("True Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected Reported", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~decay) +
  theme_minimal() +
  theme(legend.position = "none")

## Detector
detector.decay <- df.unif %>%
  filter(role=="Detector", alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(BS)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~decay) +
  theme_minimal() +
  theme(legend.position = "none")

detector2.decay <- df.unif %>%
  filter(role=="Detector2", alpha==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(Lie)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~decay) +
  theme_minimal() +
  theme(legend.position = "none")

grid.arrange(liar.decay, detector.decay, detector2.decay, nrow=3)
```

## Varying alpha (soft max)

```{r}
## Liar
liar.alpha <- df.unif %>%
  filter(role=="Liar", decay==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_abline(intercept = 0, slope = 1, colour="forestgreen", linetype=2) +
  geom_line(alpha=0.9) +
  scale_x_continuous("True Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected Reported", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~alpha) +
  theme_minimal() +
  theme(legend.position = "none")

## Detector
detector.alpha <- df.unif %>%
  filter(role=="Detector", decay==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(BS)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~alpha) +
  theme_minimal() +
  theme(legend.position = "none")

detector2.alpha <- df.unif %>%
  filter(role=="Detector2", decay==0.25, beta==0.8) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(Lie)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~alpha) +
  theme_minimal() +
  theme(legend.position = "none")

grid.arrange(liar.alpha, detector.alpha, detector2.alpha, nrow=3)
```

## Varying beta (proportion of uniform marble drawing)

```{r}
## Liar
liar.beta <- df.unif %>%
  filter(role=="Liar", decay==0.25, alpha==0.25) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_abline(intercept = 0, slope = 1, colour="forestgreen", linetype=2) +
  geom_line(alpha=0.9) +
  scale_x_continuous("True Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected Reported", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~beta) +
  theme_minimal() +
  theme(legend.position = "none")

## Detector
detector.beta <- df.unif %>%
  filter(role=="Detector", decay==0.25, alpha==0.25) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(BS)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~beta) +
  theme_minimal() +
  theme(legend.position = "none")

detector2.beta <- df.unif %>%
  filter(role=="Detector2", decay==0.25, alpha==0.25) %>%
  mutate(p = paste("p =", p)) %>%
  ggplot(aes(x=ks, y=val, colour=p)) +
  geom_line(alpha=0.9) +
  scale_x_continuous("Reported Marbles Drawn", breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Expected P(Lie)", limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff) +
  facet_wrap(~beta) +
  theme_minimal() +
  theme(legend.position = "none")

grid.arrange(liar.beta, detector.beta, detector2.beta, nrow=3)
```


# Player Scores

```{r}
bs.final %>%
  filter(trialNumber == 100) %>%
  gather("playerScore","totalScore",15:16) %>%
  mutate(playerScore = recode(playerScore, playerTotalScore = "human", oppTotalScore = "computer")) %>%
  ggplot(aes(x=totalScore, fill=playerScore)) +
  geom_density(alpha=0.5) +
  ggtitle("Total Score")
```

```{r}
bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  group_by(subjID) %>%
  summarise(propLie=sum(drawnRed!=reportedDrawn)/n()) %>%
  arrange(propLie) %>%
  ggplot(aes(x=propLie)) +
  geom_histogram(fill="black", bins=20) +
  ggtitle("Distribution of Lying Proportions") +
  theme_minimal()
```

```{r}
bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  group_by(subjID) %>%
  summarise(propBS=sum(callBS=="True")/n()) %>%
  arrange(propBS) %>%
  ggplot(aes(x=propBS)) +
  geom_histogram(fill="black", bins=20) +
  ggtitle("Distribution of BS Calling Proportions") +
  theme_minimal()
```

```{r}
bs.final %>%
  filter(roleCurrent=="bullshitter") %>%
  mutate(Actual = drawnRed,
         Reported = reportedDrawn) %>%
  select(probabilityRed, Actual, Reported) %>%
  gather("key", "value", 2:3) %>%
  ggplot(aes(x=value, fill=key)) +
  geom_density(alpha=0.5, adjust=2) +
  facet_wrap(~probabilityRed) +
  theme_minimal()
ggsave("img/distrComp_actualvsreported.png")
```

```{r}
bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  group_by(probabilityRed, reportedDrawn) %>%
  summarise(propBS = sum(callBS=="True")/n()) %>%
  ggplot(aes(x=reportedDrawn, y=propBS, colour=as.factor(probabilityRed))) +
  geom_point() +
  geom_smooth(family="binomial")
```

```{r}
bs.final %>%
  filter(roleCurrent=="bullshitter") %>%
  group_by(drawnRed, reportedDrawn, probabilityRed) %>%
  summarise(count = n()) %>%
  ungroup() %>%
  group_by(drawnRed, probabilityRed) %>%
  mutate(propFreq = count/sum(count)) %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn, fill=propFreq)) +
  geom_tile() +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(~ as.factor(probabilityRed)) +
  theme_bw()
ggsave("img/lies_tile.png")
```

```{r}
lieResults <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n()),
            n=n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=drawnRed, y=mean, colour=probabilityRed.txt, fill=probabilityRed.txt)) +
  geom_abline(intercept = 0, slope = 1, colour="forestgreen", linetype=2, size=3) +
  geom_ribbon(aes(ymin=mean-se, ymax=mean+se), alpha=0.3) +
  #geom_errorbar(aes(ymin=mean-se, ymax=mean+se), size=1.5, width=.4) +
  geom_line(size=1.5) +
  geom_point(pch=21, stroke=1, size=3, colour="black", alpha=0.8) +
  ggtitle("Marble-Sampler (Liar)") +
  scale_x_continuous("True Marbles Drawn", limits=c(-0.2,10.2), breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Reported Marbles Drawn", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values = condColors.diff) +
  scale_fill_manual(values = condColors.diff) +
  guides(colour=guide_legend(title="")) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(plot.title = element_text(size=28),
        axis.title = element_text(size=18),
        axis.text = element_text(size=18))
ggsave("img/actual_vs_reported.png", lieResults)

detectResults <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, reportedDrawn) %>%
  summarise(prop = (sum(callBS == "True")+1)/(n()+2),
            se = sqrt((prop*(1-prop)/n())),
            n = n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=reportedDrawn, y=prop, colour=probabilityRed.txt, fill=probabilityRed.txt)) +
  #geom_errorbar(aes(ymin=prop-se, ymax=prop+se), size=1.5, width=.4) +
  geom_ribbon(aes(ymin=prop-se, ymax=prop+se), alpha=0.3) +
  geom_line(size=1.5) +
  geom_point(pch=21, stroke=1, size=3, colour="black", alpha=0.8) +
  ggtitle("Responder (Detector)") +
  scale_x_continuous("Reported Marbles Drawn", limits=c(-0.2,10.2), breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Proportion Called BS", limits=c(0,1)) +
  scale_colour_manual(values = condColors.diff, guide="none") +
  scale_fill_manual(values = condColors.diff) +
  guides(fill=guide_legend(title="")) +
  theme_minimal() +
  theme(plot.title = element_text(size=28),
        axis.title = element_text(size=18),
        axis.text = element_text(size=18))
ggsave("img/probBS.png", detectResults)

both <- plot_grid(lieResults, detectResults, align = "h", ncol = 2, rel_widths = c(9/20, 11/20))
both
ggsave("img/expt4_colour.png", both, height=5, width=10)
```

```{r}
condColors = c("p = 0.2" = "blue",
               "p = 0.5" = "blue",
               "p = 0.8" = "red")

lieSubset <- bs.final %>%
  filter(roleCurrent == "bullshitter", probabilityRed == 0.5) %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n()),
            n=n())

lieResults <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n()),
            n=n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=drawnRed, y=mean, colour=probabilityRed.txt, fill=probabilityRed.txt)) +
  geom_ribbon(aes(ymin=mean-se, ymax=mean+se), alpha=0.5) +
  geom_abline(intercept = 0, slope = 1, colour="forestgreen", linetype=2, size=3) +
  geom_line(size=2.5, alpha=0.8) +
  geom_line(data=lieSubset, aes(x=drawnRed, y=mean), colour="red", size=2.5, linetype=2, alpha=0.8) +
  #geom_errorbar(aes(ymin=mean-se, ymax=mean+se), size=0.8, width=.4, alpha=0.8) +
  #geom_errorbar(data=lieSubset, aes(ymin=mean-se, ymax=mean+se), colour="red", size=0.8, width=.4, alpha=0.8) +
  #geom_linerange(aes(ymin=mean-se, ymax=mean+se), size=1, alpha=0.8) +
  geom_point(colour="black", pch=21, size=5, alpha=0.8) +
  geom_point(data=lieSubset, aes(x=drawnRed, y=mean), pch=21, fill="purple", colour="black", size=5, alpha=0.8) +
  ggtitle("Marble-Sampler (Liar)") +
  scale_x_continuous("True Marbles Drawn", limits=c(-0.2,10.2), breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Reported Marbles Drawn", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values = condColors) +
  scale_fill_manual(values = condColors.diff) +
  guides(colour=guide_legend(title="")) +
  theme_minimal() +
  theme(legend.position = "none") +
  theme(plot.title = element_text(size=24),
        axis.title = element_text(size=16),
        axis.text = element_text(size=12))
ggsave("img/actual_vs_reported.png", lieResults)

detectSubset <- bs.final %>%
  filter(roleCurrent == "bullshitDetector", probabilityRed == 0.5) %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, reportedDrawn) %>%
  summarise(prop = (sum(callBS == "True")+1)/(n()+2),
            se = sqrt((prop*(1-prop)/n())),
            n = n())

detectResults <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, reportedDrawn) %>%
  summarise(prop = (sum(callBS == "True")+1)/(n()+2),
            se = sqrt((prop*(1-prop)/n())),
            n = n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=reportedDrawn, y=prop, colour=probabilityRed.txt, fill=probabilityRed.txt)) +
  geom_ribbon(aes(ymin=prop-se, ymax=prop+se), alpha=0.5) +
  geom_line(size=2.5, alpha=0.8) +
  geom_line(data=detectSubset, aes(x=reportedDrawn, y=prop), colour="red", size=2.5, linetype=2, alpha=0.8) +
  #geom_errorbar(aes(ymin=prop-se, ymax=prop+se), width=.4) +
  #geom_errorbar(data=detectSubset, aes(ymin=prop-se, ymax=prop+se), colour="red", size=0.8, width=.4, alpha=0.8) +
  #geom_linerange(aes(ymin=prop-se, ymax=prop+se), size=1, alpha=0.8) +
  geom_point(aes(fill=probabilityRed.txt), colour="black", pch=21, size=5, alpha=0.8) +
  geom_point(data=detectSubset, aes(x=reportedDrawn, y=prop), pch=21, fill="purple", colour="black", size=5, alpha=0.8) +
  ggtitle("Responder (Detector)") +
  scale_x_continuous("Reported Marbles Drawn", limits=c(-0.2,10.2), breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Proportion Called BS", limits=c(0,1)) +
  scale_colour_manual(values = condColors, guide="none") +
  scale_fill_manual(values = condColors.diff) +
  guides(fill=guide_legend(title="")) +
  theme_minimal() +
  theme(plot.title = element_text(size=24),
        axis.title = element_text(size=16),
        axis.text = element_text(size=12))
ggsave("img/probBS.png", detectResults)

both <- plot_grid(lieResults, detectResults, align = "h", ncol = 2, rel_widths = c(9/20, 11/20))
both
ggsave("img/expt4_colour2_2.png", both, height=5, width=10)
```

# Model Predictions Feeding in Human Results

```{r}
# "template" for tidyr complete() function
template <- data.frame(probabilityRed = rep(0,11),
                       drawnRed = rep(0,11),
                       reportedDrawn = 0:10,
                       n = rep(0,11))

liePropsDF <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  group_by(probabilityRed, drawnRed, reportedDrawn) %>%
  summarise(n=n()) 

liePropsDF <- bind_rows(template,liePropsDF) %>%
  complete(probabilityRed, drawnRed, reportedDrawn, fill=list(n=0)) %>%
  filter(probabilityRed != 0) %>%
  group_by(probabilityRed, drawnRed) %>%
  mutate(total = sum(n),
         proportion = n / total)

LIE <- 1-diag(numMarbles+1)
# equivalent to output of p.L_ksay.k.r
df0.2 <- liePropsDF %>%
  filter(probabilityRed == 0.2)
mat0.2 <- matrix(df0.2$proportion, nrow=11)
# output p_t.ksay.r
P.K <- matrix(rep(p.k(0:numMarbles, 0.2), each=numMarbles+1), nrow=numMarbles+1)
lie0.2 <- rowSums(P.K*mat0.2*LIE)/rowSums(P.K*mat0.2)
# output p.D_bs.ksay.r
detect0.2 <- mapply(p.D_bs.ksay.r, 0:numMarbles, 0.2, lie0.2)

df0.5 <- liePropsDF %>%
  filter(probabilityRed == 0.5)
mat0.5 <- matrix(df0.5$proportion, nrow=11)
P.K <- matrix(rep(p.k(0:10, 0.5), each=10+1), nrow=10+1)
lie0.5 <- rowSums(P.K*mat0.5*LIE)/rowSums(P.K*mat0.5)
detect0.5 <- mapply(p.D_bs.ksay.r, 0:numMarbles, 0.5, lie0.5)

df0.8 <- liePropsDF %>%
  filter(probabilityRed == 0.8)
mat0.8 <- matrix(df0.8$proportion, nrow=11)
P.K <- matrix(rep(p.k(0:10, 0.8), each=10+1), nrow=10+1)
lie0.8 <- rowSums(P.K*mat0.8*LIE)/rowSums(P.K*mat0.8)
detect0.8 <- mapply(p.D_bs.ksay.r, 0:numMarbles, 0.8, lie0.8)

data.frame(p=c(rep(0.2,11), rep(0.5,11), rep(0.8,11)),
           ksay=rep(0:10,3),
           bs=c(detect0.2, detect0.5, detect0.8)) %>%
  mutate(probabilityRed.txt = paste("p =", p)) %>%
  ggplot(aes(x=ksay, y=bs, colour=probabilityRed.txt)) +
  geom_line() +
  ggtitle("Model Prediction BS Plugging in Human Data") +
  scale_y_continuous(limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff)

data.frame(p=c(rep(0.2,11), rep(0.5,11), rep(0.8,11)),
           ksay=rep(0:10,3),
           lie=c(lie0.2, lie0.5, lie0.8)) %>%
  mutate(probabilityRed.txt = paste("p =", p)) %>%
  ggplot(aes(x=ksay, y=lie, colour=probabilityRed.txt)) +
  geom_line() +
  ggtitle("Model Prediction Lie Plugging in Human Data") +
  scale_y_continuous(limits=c(0,1)) +
  scale_colour_manual(values=condColors.diff)
```

```{r}
lieProp <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(prop = sum(drawnRed == reportedDrawn)/n(),
            se = prop*(1-prop)/sqrt(n()),
            n = n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=drawnRed, y=prop, colour=probabilityRed.txt)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=prop-se, ymax=prop+se), width=.3) +
  scale_x_continuous("Actual Marbles Drawn", limits=c(-0.2,10.2)) +
  scale_y_continuous("Proportion of True Marbles Reported", limits=c(0,1)) +
  guides(colour=guide_legend(title="")) +
  theme_minimal()
  
lieVals <- bs.final %>%
  filter(roleCurrent == "bullshitter", drawnRed != reportedDrawn) %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n()),
            n=n()) %>%
  filter(n > 3) %>%
  ggplot(aes(x=drawnRed, y=mean, colour=probabilityRed.txt)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3) +
  geom_abline(intercept = 0, slope = 1, colour="red", linetype=2) +
  scale_x_continuous("Actual Marbles Drawn", limits=c(-0.2,10.2)) +
  scale_y_continuous("Reported Marbles Drawn", limits=c(0,10)) +
  guides(colour=guide_legend(title="")) +
  theme_minimal()

grid.arrange(lieProp, lieVals, nrow=2)
ggsave("img/liePropVals.png", grid.arrange(lieProp, lieVals, nrow=2))
```

# Model vs Human Comparison

```{r}
modelComp <- df.unif %>%
  filter(decay==0.25, alpha==0.25, beta==0.8) %>%
  mutate(k = ks,
         mean.model = val,
         se.model = se) %>%
  select(role, p, k , mean.model, se.model)

humanCompLie <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(k = drawnRed,
         p = probabilityRed) %>%
  group_by(p, k, roleCurrent) %>%
  summarise(mean.human = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se.human = sd/sqrt(n()),
            n=n()) %>%
  mutate(role = "Liar") %>%
  select(role, p, k , mean.human, se.human)
humanCompDetect <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(k = reportedDrawn,
         p = probabilityRed) %>%
  group_by(p, k, roleCurrent) %>%
  summarise(mean.human = (sum(callBS == "True")+1)/(n()+2),
            se.human = sqrt((mean.human*(1-mean.human)/n())),
            n=n()) %>%
  mutate(role = "Detector") %>%
  select(role, p, k , mean.human, se.human)
humanComp <- bind_rows(humanCompLie, humanCompDetect)

modelVsHuman <- left_join(modelComp, humanComp, by=c("role", "p", "k"))

lieComp <- modelVsHuman %>%
  filter(role=="Liar") %>%
  mutate(p.txt = paste("p =", p)) %>%
  ggplot(aes(x=mean.model, y=mean.human, colour=p.txt)) +
  geom_errorbar(aes(ymin=mean.human-se.human, ymax=mean.human+se.human), width=.1) +
  geom_errorbarh(aes(xmin=mean.model-se.model, xmax=mean.model+se.model), height=.1) +
  geom_abline(intercept = 0, slope = 1, linetype=2) +
  ggtitle("Liar") +
  scale_x_continuous("Model", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_y_continuous("Human", limits=c(0,10), breaks=c(0,2,4,6,8,10)) +
  scale_colour_manual(values = condColors.diff) +
  theme_minimal() +
  theme(legend.position = "none",
        plot.title = element_text(size=28),
        axis.title = element_text(size=18),
        axis.text = element_text(size=18))

detectComp <- modelVsHuman %>%
  filter(role=="Detector") %>%
  mutate(p.txt = paste("p =", p)) %>%
  ggplot(aes(x=mean.model, y=mean.human, colour=p.txt)) +
  geom_errorbar(aes(ymin=mean.human-se.human, ymax=mean.human+se.human), width=.02) +
  geom_errorbarh(aes(xmin=mean.model-se.model, xmax=mean.model+se.model), height=.02) +
  geom_abline(intercept = 0, slope = 1, linetype=2) +
  ggtitle("Detector") +
  scale_x_continuous("Model", limits=c(0,1)) +
  scale_y_continuous("Human", limits=c(0,1)) +
  scale_colour_manual(values = condColors.diff) +
  guides(colour=guide_legend(title="")) +
  theme_minimal() +
  theme(plot.title = element_text(size=28),
        axis.title = element_text(size=18),
        axis.text = element_text(size=18))

bothComp <- plot_grid(lieComp, detectComp, align = "h", ncol = 2, rel_widths = c(9/20, 11/20))
bothComp
ggsave("img/modelComparison.png", bothComp, height=5, width=10)
```

```{r}
humanDetect <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(callBS = ifelse(callBS == "False", FALSE, TRUE),
         avgRed = probabilityRed * 10,
         reportedDrawn.sq = reportedDrawn ^ 2,
         probabilityRed.f = relevel(as.factor(probabilityRed), ref="0.5"))
humanDetect %>%
  group_by(subjID, probabilityRed.f) %>%
  summarise(count=n())

# contrasts - FALSE set to 0
contrasts(humanDetect$probabilityRed.f)
model.BS.quad <- glmer(callBS ~ poly(reportedDrawn, 2)* 
                       probabilityRed.f + (1|subjID), data=humanDetect, family="binomial")
summary(model.BS.quad)

# checks if model converges
with(model.BS.quad@optinfo$derivs,max(abs(solve(Hessian,gradient)))<2e-3)


model.BS.lin <- glmer(callBS ~ poly(reportedDrawn,1)* 
                       probabilityRed.f + (1|subjID), data=humanDetect, family="binomial")
summary(model.BS.lin)

anova(model.BS.lin, model.BS.quad, test="Chisq")

lm.coefs <- summary(model.BS.quad)$coef[,"Estimate"]

quadratic <- function(a, b, c){
  plus <- (-b + sqrt(b^2 - 4*a*c)) / (2*a)
  minus <- (-b - sqrt(b^2 - 4*a*c)) / (2*a)
  return(c(plus, minus))
}
est.b <- function(a, b, c){
  
}
upward <- function(a){
  a > 0
}
quadratic(1,2,1)
stdform.0.2 <- quadratic(lm.coefs["poly(reportedDrawn, 2)2"], lm.coefs["poly(reportedDrawn, 2)1"], lm.coefs["(Intercept)"]) 
dir.0.2 <- upward(lm.coefs["poly(reportedDrawn, 2)2"])
stdform.0.5 <- quadratic(lm.coefs["poly(reportedDrawn, 2)2"]+lm.coefs["poly(reportedDrawn, 2)2:as.factor(probabilityRed)0.5"], 
                         lm.coefs["poly(reportedDrawn, 2)1"]+lm.coefs["poly(reportedDrawn, 2)1:as.factor(probabilityRed)0.5"],
                         lm.coefs["(Intercept)"]+lm.coefs["as.factor(probabilityRed)0.5"]) 
dir.0.5 <- upward(lm.coefs["poly(reportedDrawn, 2)2"]+lm.coefs["poly(reportedDrawn, 2)2:as.factor(probabilityRed)0.5"])
stdform.0.8 <- quadratic(lm.coefs["poly(reportedDrawn, 2)2"]+lm.coefs["poly(reportedDrawn, 2)2:as.factor(probabilityRed)0.8"], 
                         lm.coefs["poly(reportedDrawn, 2)1"]+lm.coefs["poly(reportedDrawn, 2)1:as.factor(probabilityRed)0.8"], 
                         lm.coefs["(Intercept)"]+lm.coefs["as.factor(probabilityRed)0.8"]) 
dir.0.8 <- upward(lm.coefs["poly(reportedDrawn, 2)2"]+lm.coefs["poly(reportedDrawn, 2)2:as.factor(probabilityRed)0.8"])

# thresh.x1 <- function(x2){
#   (-lm.coefs["(Intercept)"]-lm.coefs["probabilityRed"]*x2)/(lm.coefs["reportedDrawn"]+lm.coefs["reportedDrawn:probabilityRed"]*x2)
# }
# thresh.x1(c(0.2,0.5,0.8)) #returns predicted k* when P(BS|k*) = {0.2, 0.5, 0.8}

logitToProb <- function(logit){
  exp(logit) / (1+exp(logit))
}

probToLogit <- function(prob){
  log(prob / (1 - prob))
}
```


## MLE Analysis


```{r warning=FALSE}
logitToProb <- function(logit){
  exp(logit) / (1+exp(logit))
}

probToLogit <- function(prob){
  log(prob / (1 - prob))
}

quadratic <- function(x, a, b, c){
  a*(x-b)^2+c
}

logisticModel <- function(x, a, b, c){
  logitToProb(pmin(10, pmax(-10, quadratic(x, a, b, c))))
}

lapsePlusLogistic <- function(x, a, b, c, alph){
  alph2 = logitToProb(alph)
  a = exp(a)
  alph2/2 + (1-alph2)*logisticModel(x, a, b, c)
}

loglik <- function(x, y, a, b, c, alph){
  sum(
    dbinom(y, 1, lapsePlusLogistic(x, a, b, c, alph), log=T)
  )
}

brutefit <- function(tmp){
  nLL <- function(a, b, c, alph){
    -loglik(tmp$reportedDrawn, tmp$callBS, a, b, c, alph)+
      (a-1)^2+
      (b-5)^2+
      c^2+
      (alph+2)^2
  }

  iter = 0
  fits = NULL
  fit = NULL
  while(is.null(fits)){
    try(fit <- summary(mle(nLL,
                           start=list(a=rnorm(1, 0, 3),
                                      b=rnorm(1, 0, 3),
                                      c=rnorm(1, 0, 3),
                                      alph=rnorm(1, -2, 3)), method = 'BFGS'), TRUE))
    iter = iter+1

    if(! is.null(fit)){
      fits <- c(tmp$probabilityRed[1], -0.5*fit@m2logL, length(tmp$reportedDrawn), fit@coef[,"Estimate"], fit@coef[,"Std. Error"])
    } else {
      if(iter>100){
        fits <- c(tmp$probabilityRed[1], -9999, 0, 0, 0, 0, 0, 0, 0, 0, 0)
      }
    }
  }
  names(fits) <- c("probabilityRed", "logL", "n", "est.a", "est.b", "est.c", "est.alph", "se.a", "se.b", "se.c", "se.alph")
  return(fits)
}

ps = c(-0.5, 0.5, -0.5, 0.5, -0.5, 0.5, -5, -0.5)
names(ps) <- c("min_a", "max_a", "min_b", "max_b", "min_c", "max_c", "min_alph", "max_alph")
quadr.fits <- data.frame(do.call(rbind, by(humanDetect, humanDetect$probabilityRed, brutefit)))
print(paste("Failed quadratic fits:", sum(quadr.fits$logL==-9999)))


quadr.est <- quadr.fits %>%
  select(1:7) %>%
  gather("variable", "estimate", 4:7) %>%
  mutate(variable = gsub("est.", "", variable))
quadr.se <- quadr.fits %>%
  select(-c(4:7)) %>%
  gather("variable", "std.err", 4:7) %>%
  mutate(variable = gsub("se.", "", variable))
quadr.summ <- left_join(quadr.est, quadr.se, by=c("probabilityRed","logL","n","variable"))
quadr.summ %>%
  mutate(z.value = estimate/std.err,
         p.value = ifelse(pnorm(-abs(z.value)) > .000001, pnorm(-abs(z.value)), "<.000001")) %>%
  arrange(probabilityRed, variable)

# y = a(x-b)^2 + c
b_0.2 <- quadr.summ %>%
  filter(variable == "b", probabilityRed == 0.2)
b_0.5 <- quadr.summ %>%
  filter(variable == "b", probabilityRed == 0.5)
b_0.8 <- quadr.summ %>%
  filter(variable == "b", probabilityRed == 0.8)

# one sided 2 sample t test with pooled variance
wald.z.test <- function(m1, sd1, m2, sd2){
  z <- (m1 - m2) / sqrt(sd1^2 + sd2^2)
  p <- pnorm(abs(z), lower.tail=F)
  return(data.frame(m1, sd1, m2, sd2, z, p))
}

wald.z.test(b_0.5$estimate, b_0.5$std.err, b_0.2$estimate, b_0.2$std.err)
wald.z.test(b_0.5$estimate, b_0.5$std.err, b_0.8$estimate, b_0.8$std.err)

quadr.plot <- data.frame(x=rep(0:10,3), 
           p=as.factor(c(rep(0.2,11), rep(0.5,11), rep(0.8,11))),
           a=c(rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.8],11)),
           b=c(rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.8],11)),
           c=c(rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.8],11)),
           alph=c(rep(quadr.fits$est.alph[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.alph[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.alph[quadr.fits$probabilityRed==0.8],11))) %>%
  mutate(prob=lapsePlusLogistic(x, a, b, c, alph))
ggplot(quadr.plot, aes(x=x, y=prob, colour=p)) +
  geom_line() +
  scale_y_continuous(limits=c(0,1))
ggsave("img/quadraticFit.png")

exptDetect <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, reportedDrawn) %>%
  summarise(prop = (sum(callBS == "True")+1)/(n()+2),
            se = sqrt((prop*(1-prop)/n())),
            n = n()) %>%
  filter(n > 3) %>%
  mutate(fit="experiment")
quadr.plot2 <- data.frame(probabilityRed.txt = paste("p =", quadr.plot$p),
                          reportedDrawn = quadr.plot$x,
                          prop = quadr.plot$prob,
                          se = NA,
                          n = NA,
                          fit = "model")
quadr.plot_full <- bind_rows(exptDetect, quadr.plot2)
ggplot(data=quadr.plot_full, aes(x=reportedDrawn, y=prop, colour=probabilityRed.txt, linetype=fit)) +
  geom_point(data=filter(quadr.plot_full, fit=="experiment")) +
  geom_line() +
  geom_errorbar(data=filter(quadr.plot_full, fit=="experiment"), aes(x=reportedDrawn, colour=probabilityRed.txt, min=prop-se, max=prop+se), width=.3) +
  scale_x_continuous("Reported Marbles Drawn", limits=c(-0.2,10.2)) +
  scale_y_continuous("Proportion BS Called", limits=c(0,1)) +
  guides(colour=guide_legend(title="")) +
  theme_minimal()
ggsave("img/fit_expt_model.png")
```

# Artificial Data

```{r include=FALSE}
artifParabola <- function(p, ksay){
  runif(1) < logitToProb(0.06*(ksay-7*p)^2-1.5)
}
artificialResp <- mapply(artifParabola, humanDetect$probabilityRed, humanDetect$reportedDrawn)

artificial <- data.frame(probabilityRed = humanDetect$probabilityRed,
                         reportedDrawn = humanDetect$reportedDrawn,
                         callBS = artificialResp)

#artificial data, sanity check
quadr.fits <- data.frame(do.call(rbind, by(artificial, artificial$probabilityRed, brutefit)))
print(paste("Failed quadratic fits:", sum(quadr.fits$logL==-9999)))

quadr.plot <- data.frame(x=rep(0:10,3), 
           p=as.factor(c(rep(0.2,11), rep(0.5,11), rep(0.8,11))),
           a=c(rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.a[quadr.fits$probabilityRed==0.8],11)),
           b=c(rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.b[quadr.fits$probabilityRed==0.8],11)),
           c=c(rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.2],11),
               rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.5],11),
               rep(quadr.fits$est.c[quadr.fits$probabilityRed==0.8],11))) %>%
  mutate(y=a*(x-b)^2+c,
         prob=logitToProb(y))
ggplot(quadr.plot, aes(x=x, y=prob, colour=p)) +
  geom_line() +
  scale_y_continuous(limits=c(0,1))
```




```{r include=FALSE}
subjModels <- data.frame(subjID=character(),
                         probabilityRed=numeric(),
                         variable=character(),
                         Estimate=numeric(),
                         Std.Error=numeric(),
                         z.value=numeric(),
                         p.value=numeric())
for(s in unique(humanDetect$subjID)){
  subjDat <- humanDetect %>%
    filter(subjID == s)
  subjModel <- glm(callBS ~ I(reportedDrawn^2) + reportedDrawn, data=subjDat, family="binomial")
  subjModels <- bind_rows(subjModels, 
                          data.frame(subjID=s, 
                                     probabilityRed=unique(subjDat$probabilityRed),
                                     variable=c("Intercept","reportedDrawn.sq", "reportedDrawn"),
                                     Estimate=summary(subjModel)$coef[,"Estimate"],
                                     Std.Error=summary(subjModel)$coef[,"Std. Error"],
                                     z.value=summary(subjModel)$coef[,"z value"],
                                     p.value=summary(subjModel)$coef[,"Pr(>|z|)"]))
  
}
subjModels
```

```{r include=FALSE}
condModels <- data.frame(probabilityRed=numeric(),
                         variable=character(),
                         Estimate=numeric(),
                         Std.Error=numeric(),
                         z.value=numeric(),
                         p.value=numeric(),
                         signif=logical())
for(c in unique(humanDetect$probabilityRed)){
  condDat <- humanDetect %>%
    filter(probabilityRed == c)
  condModel <- glmer(callBS ~ I(reportedDrawn^2) + reportedDrawn + (1 | subjID), data=condDat, family="binomial")
  condModels <- bind_rows(condModels, 
                          data.frame(probabilityRed=c,
                                     variable=c("Intercept","reportedDrawn.sq", "reportedDrawn"),
                                     Estimate=summary(condModel)$coef[,"Estimate"],
                                     Std.Error=summary(condModel)$coef[,"Std. Error"],
                                     z.value=summary(condModel)$coef[,"z value"],
                                     p.value=summary(condModel)$coef[,"Pr(>|z|)"],
                                     signif=summary(condModel)$coef[,"Pr(>|z|)"] < .05))
}
condModels
```

```{r include=FALSE}
model.BS.me.c <- glmer(callBS ~ (reportedDrawn.sq + reportedDrawn) * 
                       probabilityRed + 
                       (1|subjID), data=humanDetect, family="binomial")
summary(model.BS.me.c)
```


