---
title: "Bullshitter Expt 1"
author: "Lauren Oey"
date: "1/14/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
knitr::opts_chunk$set(echo = TRUE)

bs <- read.csv("raw.csv")
glimpse(bs)

bs <- bs %>%
  mutate(lie = drawnRed != reportedDrawn,
         player.bullshitter = ifelse(roleCurrent == "bullshitter", "human", "computer"),
         player.bullshitDetector = ifelse(roleCurrent == "bullshitDetector", "human", "computer"))
```

```{r}
bs %>%
  filter(trialNumber == 40) %>%
  gather("playerScore","totalScore",13:14) %>%
  mutate(playerScore = recode(playerScore, playerTotalScore = "human", oppTotalScore = "computer")) %>%
  ggplot(aes(x=totalScore, fill=playerScore)) +
  geom_density(alpha=0.5) +
  ggtitle("Total Score")
```

```{r}
bs %>%
  filter(trialNumber == 40) %>%
  mutate(scoreDifferential = playerTotalScore - oppTotalScore) %>%
  ggplot(aes(x=scoreDifferential)) +
  geom_histogram() +
  ggtitle("Distribution of Score Differential (Human - Computer)")

# Participants who scored more than 150 points fewer than the computer
bs %>%
  filter(trialNumber == 40) %>%
  mutate(scoreDifferential = playerTotalScore - oppTotalScore) %>%
  filter(scoreDifferential < -150) %>%
  select(subjID, playerTotalScore, oppTotalScore, scoreDifferential) %>%
  arrange(desc(scoreDifferential))
```

```{r}
bs %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(badLie = drawnRed > reportedDrawn) %>%
  group_by(subjID, badLie) %>%
  summarise(badLie.count = n()) %>%
  filter(badLie) %>%
  mutate(badLie.prop = badLie.count / 20) %>%
  ggplot(aes(x=badLie.prop)) + 
  geom_bar() +
  ggtitle("Proportion of Bad Lies (Reported < Actual)")

# Participants who generated bad lies for more than 1/4 of their turns
excluded <- bs %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(badLie = drawnRed > reportedDrawn) %>%
  group_by(subjID, badLie) %>%
  summarise(badLie.count = n()) %>%
  filter(badLie) %>%
  mutate(badLie.prop = badLie.count / 20) %>%
  filter(badLie.prop > .2)
excluded %>%
  select(subjID, badLie.prop) %>%
  arrange(desc(badLie.prop))
```

```{r}
bs.final <- bs %>%
  filter(!subjID %in% excluded$subjID)

length(unique(bs.final$subjID))
```

```{r}
ggplot(bs.final, aes(x=drawnRed, y=reportedDrawn, colour=callBS)) +
  geom_jitter(alpha = 0.5) +
  stat_smooth(method="lm", formula=y~x+I(x^2), size=1) +
  ggtitle("Lie Production") +
  facet_wrap(~player.bullshitter) +
  theme_bw()
```

```{r}
bs.final %>%
  group_by(subjID, player.bullshitter, drawnRed) %>%
  summarise(propLie = sum(lie)/n()) %>%
  ggplot(aes(x=drawnRed, y=propLie)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Proportion of Lying") + 
  facet_wrap(~player.bullshitter)
```

```{r}
bs.final %>%
  group_by(subjID, player.bullshitDetector, reportedDrawn) %>%
  summarise(propCallBS = sum(callBS == "True")/n()) %>%
  ggplot(aes(x=reportedDrawn, y=propCallBS)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Proportion of BS Calling") + 
  facet_wrap(~player.bullshitDetector)
```

```{r}
bs.final %>%
  mutate(callBS = ifelse(callBS == "True", "called BS", "didn't call BS"),
         lie = ifelse(lie, "Lied", "Told the Truth")) %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn)) +
  geom_jitter() +
  facet_grid(callBS ~ lie)
```

```{r}
ggplot(bs.final, aes(x=reportedDrawn, fill=callBS)) +
  geom_density(alpha=0.5, adjust = 2) +
  ggtitle("Distribution of Truth vs Lies") +
  facet_wrap(~player.bullshitter)
```
