---
title: "Bullshitter Expt 2 (Pilot)"
author: "Lauren Oey"
date: "1/15/2019"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(lme4)
knitr::opts_chunk$set(echo = TRUE)

bs <- read.csv("raw.csv")
glimpse(bs)

bs <- bs %>%
  mutate(lie = drawnRed != reportedDrawn,
         player.bullshitter = ifelse(roleCurrent == "bullshitter", "human", "computer"),
         player.bullshitDetector = ifelse(roleCurrent == "bullshitDetector", "human", "computer"))
```

```{r}
bs %>%
  filter(trialNumber == 40) %>%
  gather("playerScore","totalScore",13:14) %>%
  mutate(playerScore = recode(playerScore, playerTotalScore = "human", oppTotalScore = "computer")) %>%
  ggplot(aes(x=totalScore, fill=playerScore)) +
  geom_density(alpha=0.5) +
  ggtitle("Total Score")
```

```{r}
bs %>%
  filter(trialNumber == 40) %>%
  mutate(scoreDifferential = playerTotalScore - oppTotalScore) %>%
  ggplot(aes(x=scoreDifferential)) +
  geom_histogram(aes(y=..density..)) +
  ggtitle("Distribution of Human Score - Computer Score") +
  scale_x_continuous("Score Differential (Human - Computer)") +
  scale_y_continuous("Density") +
  theme_bw()
ggsave("img/scoreDistribution.png")

# Participants who scored more than 150 points fewer than the computer
bs %>%
  filter(trialNumber == 40) %>%
  mutate(scoreDifferential = playerTotalScore - oppTotalScore) %>%
  filter(scoreDifferential < -150) %>%
  select(subjID, playerTotalScore, oppTotalScore, scoreDifferential) %>%
  arrange(desc(scoreDifferential))

exclude.sampling <- bs %>%
  filter(reportedDrawn > 10)
```

```{r}
bs %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(badLie = drawnRed > reportedDrawn) %>%
  group_by(subjID) %>%
  summarise(badLie.prop = sum(badLie)/n()) %>%
  ggplot(aes(x=badLie.prop)) + 
  geom_bar(aes(y = (..count..)/sum(..count..))) +
  scale_x_continuous("Proportion of Lies Produced with Reported < Actual") +
  scale_y_continuous("Proportion of Participants") +
  theme_bw()
ggsave("img/counterintuitiveLies.png")

# Participants who generated bad lies for more than 1/4 of their turns
excluded <- bs %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(badLie = drawnRed > reportedDrawn) %>%
  group_by(subjID) %>%
  summarise(badLie.prop = sum(badLie)/n())
  
excluded %>%
  filter(badLie.prop > .2) %>%
  select(subjID, badLie.prop) %>%
  arrange(desc(badLie.prop))

excluded %>%
  ungroup() %>%
  summarise(badLiar.prop = sum(badLie.prop > 0)/n())

length(unique(bs$subjID))
```

```{r}
# bs.final <- bs %>%
#   filter(!subjID %in% excluded$subjID)
bs.final <- bs %>%
  filter(!subjID %in% exclude.sampling$subjID)

length(unique(bs.final$subjID))
```

```{r}
ggplot(bs.final, aes(x=drawnRed, y=reportedDrawn)) +
  geom_jitter(alpha = 0.5) +
  stat_smooth(method="lm", formula=y~x+I(x^2), size=1) +
  ggtitle("Reported vs Actual Number of Marbles Drawn") +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(as.factor(probabilityRed)~player.bullshitter) +
  theme_bw()
ggsave("img/liesProduction_humanVsComp.png")
```

```{r}
bs.final %>%
  filter(player.bullshitter == "human") %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn)) +
  geom_jitter(alpha = 0.5) +
  stat_smooth(method="lm", formula=y~x+I(x^2), size=1) +
  ggtitle("Reported vs Actual Number of Marbles Drawn") +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(as.factor(probabilityRed)~.) +
  theme_bw()
ggsave("img/liesProduction_human.png")
```

```{r}
ggplot(bs.final, aes(x=drawnRed, y=reportedDrawn, colour=callBS)) +
  geom_jitter(alpha = 0.5) +
  stat_smooth(method="lm", formula=y~x+I(x^2), size=1) +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(as.factor(probabilityRed)~player.bullshitter) +
  theme_bw()
ggsave("img/liesProduction_callBS_humanVsComp.png")
```

```{r}
bs.final %>%
  group_by(player.bullshitDetector, drawnRed, probabilityRed, reportedDrawn) %>%
  summarise(propCallBS = sum(callBS == "True")/n(),
            count = n()) %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn, size=count, alpha=propCallBS)) +
  geom_point() +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(as.factor(probabilityRed)~player.bullshitDetector) +
  theme_bw()
ggsave("img/lies_callBS_dotsize.png")
```

```{r}
bs.final %>%
  group_by(subjID, player.bullshitter, drawnRed, probabilityRed) %>%
  summarise(propLie = sum(lie)/n()) %>%
  ggplot(aes(x=drawnRed, y=propLie)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Production") +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Proportion of Lies") +
  facet_grid(as.factor(probabilityRed)~player.bullshitter)
ggsave("img/liesProductionLogistic_humanVsComp.png")
```

```{r}
bs.final %>%
  filter(player.bullshitter == "human") %>%
  group_by(subjID, drawnRed, probabilityRed) %>%
  summarise(propLie = sum(lie)/n()) %>%
  ggplot(aes(x=drawnRed, y=propLie)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Production") +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Proportion of Lies") +
  facet_grid(as.factor(probabilityRed)~.) +
  theme_bw()
ggsave("img/liesProductionLogistic_human.png")
```

```{r}
bs.final %>%
  filter(player.bullshitter == "human") %>%
  group_by(drawnRed, probabilityRed) %>%
  summarise(propLie = sum(lie)/n()) %>%
  ggplot(aes(x=drawnRed, y=propLie)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Production") +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Proportion of Lies") +
  facet_grid(as.factor(probabilityRed)~.) +
  theme_bw()
ggsave("img/liesProductionLogistic_human_aggr.png")
```

```{r}
bs.final %>%
  group_by(subjID, player.bullshitDetector, reportedDrawn, probabilityRed) %>%
  summarise(propCallBS = sum(callBS == "True")/n()) %>%
  ggplot(aes(x=reportedDrawn, y=propCallBS)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Detection") +
  scale_x_continuous("Reported Marbles Drawn") +
  scale_y_continuous("Proportion of Lie Accusations") +
  facet_grid(as.factor(probabilityRed)~player.bullshitDetector) +
  theme_bw()
ggsave("img/liesDetection_humanVsComp.png")
```

```{r}
bs.final %>%
  filter(player.bullshitDetector == "human") %>%
  group_by(subjID, reportedDrawn, probabilityRed) %>%
  summarise(propCallBS = sum(callBS == "True")/n()) %>%
  ggplot(aes(x=reportedDrawn, y=propCallBS)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Detection") +
  scale_x_continuous("Reported Marbles Drawn") +
  scale_y_continuous("Proportion of Lie Accusations") +
  facet_grid(as.factor(probabilityRed)~.) +
  theme_bw()
ggsave("img/liesDetection_human.png")
```

```{r}
bs.final %>%
  filter(player.bullshitDetector == "human") %>%
  group_by(reportedDrawn, probabilityRed) %>%
  summarise(propCallBS = sum(callBS == "True")/n()) %>%
  ggplot(aes(x=reportedDrawn, y=propCallBS)) +
  geom_jitter() +
  geom_smooth(method="glm", method.args=list(family="quasibinomial")) +
  ggtitle("Lie Detection") +
  scale_x_continuous("Reported Marbles Drawn") +
  scale_y_continuous("Proportion of Lie Accusations") +
  facet_grid(as.factor(probabilityRed)~.) +
  theme_bw()
ggsave("img/liesDetection_human_aggr.png")
```

```{r}
bs.final %>%
  group_by(reportedDrawn, roleCurrent, probabilityRed) %>%
  summarise(propCallBS = sum(callBS == "True")/n(),
            propLie = sum(lie)/n()) %>%
  gather("action", "prop", 4:5) %>%
  mutate(player = ifelse(roleCurrent=="bullshitter" & action=="propLie" | roleCurrent=="bullshitDetector" & action=="propCallBS", "human", "computer"),
         action = recode(action, propLie="P(lie|ksay)", propCallBS="P(BS|ksay)")) %>%
  ggplot(aes(x=reportedDrawn, y=prop, colour=action)) +
  geom_line() +
  scale_x_continuous("Reported Marbles Drawn") +
  scale_y_continuous("Proportion") +
  facet_grid(as.factor(probabilityRed)~player) +
  theme_bw()
ggsave("img/human_ksay.png")
```

```{r}
bs.final %>%
  mutate(callBS = ifelse(callBS == "True", "called BS", "didn't call BS"),
         lie = ifelse(lie, "Lied", "Told the Truth")) %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn)) +
  geom_jitter() +
  facet_grid(callBS ~ lie)
```

```{r}
bs.final %>%
  group_by(player.bullshitter, drawnRed, reportedDrawn, probabilityRed) %>%
  summarise(prop.callBS = sum(callBS == "True")/n()) %>%
  ggplot(aes(x=drawnRed, y=reportedDrawn, fill=prop.callBS)) +
  geom_tile() +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  facet_grid(as.factor(probabilityRed)~player.bullshitter) +
  theme_bw()
ggsave("img/liesProduction_callBS_humanVsComp_heatmap.png")
```

```{r}
ggplot(bs.final, aes(x=reportedDrawn, fill=callBS)) +
  geom_density(alpha=0.5, adjust = 2) +
  ggtitle("Distribution of Truth vs Lies") +
  facet_grid(as.factor(probabilityRed)~player.bullshitter)
```

```{r}
bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  ggplot(aes(x=drawnRed, colour=as.factor(probabilityRed))) +
  geom_density(adjust=2) +
  scale_x_continuous("Actual Marbles Drawn") +
  guides(colour=guide_legend(title="P(Red)")) +
  theme_minimal()
ggsave("img/distr_drawnRed.png")
```

Aggregating Across Probability Conditions

```{r}
aggregated <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  group_by(drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n())) %>%
  ggplot(aes(x=drawnRed, y=mean)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3) +
  geom_abline(intercept = 0, slope = 1, colour="red", linetype=2) +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  theme_minimal()
aggregated
ggsave("img/actual_vs_reported_errorbars_collapsed.png", aggregated)
```

```{r}
byProb <- bs.final %>%
  filter(roleCurrent == "bullshitter") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, drawnRed) %>%
  summarise(mean = mean(reportedDrawn),
            sd = sd(reportedDrawn),
            se = sd/sqrt(n()),
            n=n()) %>%
  filter(n > 2) %>%
  ggplot(aes(x=drawnRed, y=mean, colour=probabilityRed.txt)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(ymin=mean-se, ymax=mean+se), width=.3) +
  geom_abline(intercept = 0, slope = 1, colour="red", linetype=2) +
  scale_x_continuous("Actual Marbles Drawn") +
  scale_y_continuous("Reported Marbles Drawn") +
  guides(colour=guide_legend(title="")) +
  theme_minimal()
byProb
ggsave("img/actual_vs_reported_errorbars.png", byProb)
```

```{r}
grid.arrange(byProb, aggregated, ncol=2)
```



```{r}
bs.final %>%
  filter(roleCurrent=="bullshitter") %>%
  mutate(Actual = drawnRed,
         Reported = reportedDrawn) %>%
  select(probabilityRed, Actual, Reported) %>%
  gather("key", "value", 2:3) %>%
  ggplot(aes(x=value, fill=key)) +
  geom_density(alpha=0.5, adjust=2) +
  facet_wrap(~probabilityRed) +
  theme_minimal()
ggsave("img/distrComp_actualvsreported.png")
```

```{r}
bs.final %>%
  filter(roleCurrent=="bullshitter") %>%
  ggplot(aes(x=reportedDrawn, fill=as.factor(drawnRed))) +
  geom_density(alpha=0.5) +
  facet_grid(probabilityRed ~.)
```


```{r}
bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(probabilityRed.txt = paste("p =", probabilityRed)) %>%
  group_by(probabilityRed.txt, reportedDrawn) %>%
  summarise(prop = (sum(callBS == "True")+1)/(n()+2),
            se = sqrt((prop*(1-prop)/n())),
            n = n()) %>%
  filter(n > 2) %>%
  ggplot(aes(x=reportedDrawn, y=prop, colour=probabilityRed.txt)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(min=prop-se, max=prop+se), width=.3) +
  scale_x_continuous("Reported Marbles Drawn", limits=c(-0.2,10.2)) +
  scale_y_continuous("Proportion BS Called", limits=c(0,1)) +
  guides(colour=guide_legend(title="")) +
  theme_minimal()
ggsave("img/probBS.png")
```

```{r}
bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  group_by(reportedDrawn) %>%
  summarise(prop = sum(callBS == "True")/n(),
            se = sqrt((prop*(1-prop)/n()))) %>%
  ggplot(aes(x=reportedDrawn, y=prop)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(min=prop-se, max=prop+se), width=.3) +
  scale_x_continuous("Reported Marbles Drawn", limits=c(-0.5,10.5)) +
  scale_y_continuous("Proportion BS Called", limits=c(0,1)) +
  theme_bw()
ggsave("img/propBS_collapsed.png")
```

```{r}
humanDetect <- bs.final %>%
  filter(roleCurrent == "bullshitDetector") %>%
  mutate(callBS = ifelse(callBS == "False", FALSE, TRUE),
         avgRed = probabilityRed * 10)

# contrasts - FALSE set to 0
model.BS.me <- glmer(callBS ~ reportedDrawn*probabilityRed + (1|subjID), data=humanDetect, family="binomial")
summary(model.BS.me)

model.BS <- glm(callBS ~ reportedDrawn*probabilityRed, data=humanDetect, family="binomial")
summary(model.BS)
lm.coefs <- summary(model.BS)$coef[,"Estimate"]

thresh.x1 <- function(x2){
  (-lm.coefs["(Intercept)"]-lm.coefs["probabilityRed"]*x2)/(lm.coefs["reportedDrawn"]+lm.coefs["reportedDrawn:probabilityRed"]*x2)
}
thresh.x1(c(0.2,0.5,0.8)) #returns predicted k* when P(BS|k*) = 0.5
```



```{r}
summary(glm(callBS ~ reportedDrawn*probabilityRed, data=humanDetect, family="binomial"))


# treat probabilityRed as factor
summary(glmer(callBS ~ reportedDrawn*as.factor(probabilityRed) + (1|subjID), data=humanDetect, family="binomial"))
```













